### ISSUE TITLE
MRtrix3 code version

### ISSUE THREAD

**Issue by Lestropie** [sina-mansour/UKB-connectomics#38]
During development, we used a git branch on *MRtrix3* to include all of the enhancements utilised in this project. However branches are mutable and guarantee of persistence is low.

There's a couple of options here:

1.  If you want for the code here to be dynamically updated to be possible to execute using the "best" code available:
    1.  Leave the *MRtrix3* `ukb` branch in place until MRtrix version `3.1.0` is released
    2.  When that release happens, change code here to pull that new MRtrix version
    3.  Delete the `ukb` *MRtrix3* branch

2.  If instead, you want this repository to be an effectively immutable reference of what was actually executed in generation of the distributed data, then either:
    1.  Modify the code here such that instead of cloning a specific *MRtrix3* branch, it points to the exact commit that the `ukb` branch currently points to; or
    2.  Delete the *MRtrix3* `ukb` branch, and then create instead a `ukb` *tag* on *MRtrix3*, that points to the same commit (unlike a branch, a tag is considered immutable)

I am in preference of 2.i. We don't expect people to be re-running this script on subjects already processed, and so we don't want to be dragging in unrelated code updates. Within point 2, 2.ii would result in creation of a new tag for all clones of the repository that does not represent an incremental update of the software as defined by semantic versioning. 2.i is only a minor change here, does not require *MRtrix3* changes (and allows me to delete that branch), and the version of *MRtrix3* used in generation of the data can be referenced as `3.0.3` plus [relevant updates](https://github.com/orgs/MRtrix3/projects/5/views/1) (see also #37).

**Comment by sina-mansour** [comment]
Thanks Rob.

Yes, I think we could replace `ukb` [here](https://github.com/sina-mansour/UKB-connectomics/blob/main/scripts/bash/mrtrix_installation.sh#L32) with the exact commit (I think it would be [dc5d004](https://github.com/MRtrix3/mrtrix3/commit/dc5d0048e5995b7c66d15ee9383c54dd9b31051a)).

This can ensure the reproducibility and traceability of the exact version used. (I'll apply this change soon)

**Comment by sina-mansour** [comment]
This is now updated to link to the [appropriate commit](https://github.com/MRtrix3/mrtrix3/commit/eeab681d3e0cb004cf1d1d31579d3892197ef5b6).
