### ISSUE TITLE
Ask for the data used for constructing functional connectivity matrix

### ISSUE THREAD

**Issue by hitrp** [sina-mansour/UKB-connectomics#42]
Dear Sina, 

Thanks for the immediate response. Just one more question, are you constructing the functional connectivity matrix based on cleaned fMRI, which has been processed with the FSL MELODIC pipeline (EPI susceptibility distortion correction, GDC, motion correction with FSL MCFLIRT, grand-mean intensity normalization, and high-pass temporal filtering) and  ICA + FIX step? If so, I think generally I don't need to worry too much about the head motion.

Best wishes,
Peng

**Comment by sina-mansour** [comment]
Hi Peng,

Yes, the functional time series are computed from the MELODIC cleaned fMRI data (as detailed [here](https://linkinghub.elsevier.com/retrieve/pii/S1053811917308613)). This should ideally reduce concerns regarding motion artifacts.

Best,
Sina
